exports.QUESTIONS_DATA = [
  {
    qid: 1,
    qowner: 'public',
    qkey: '1NT01',
    qdetail:
      'After the following biddding.   AKJx, AQxxx, Kx xx what is the opening bid ?  Think about your rebid.',
    qcorrect: '1H',
    qbad1: '1NT',
    qbad2: '1S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 2,
    qowner: 'public',
    qkey: '1NT02',
    qdetail:
      'After the following biddding.   AKx, AQxxx, KJx xx what is the opening bid ?  Think about your rebid.',
    qcorrect: '1NT',
    qbad1: '1H',
    qbad2: '1D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 3,
    qowner: 'public',
    qkey: '1NT03',
    qdetail:
      'After the following biddding.   1NT  P  2C  P,  2D  Pass.  What is your bid ?',
    qcorrect: 'Garbage Stayman',
    qbad1: 'Has long diamonds',
    qbad2: 'Transfer to hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 4,
    qowner: 'public',
    qkey: '1NT04',
    qdetail:
      'After the following biddding.   1NT  P  2C  P, 2D  P  2NT.  What is your bid ?',
    qcorrect: 'Range Finder',
    qbad1: 'Transfer to Minors',
    qbad2: 'Transfer to Diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 5,
    qowner: 'public',
    qkey: '1NT05',
    qdetail:
      'After the following biddding.   1NT  P  2C  P, 2D  P  3H.  What is your bid ?',
    qcorrect: 'Smolen 5 Spades, 4 Hearts',
    qbad1: 'Transfer to Spades',
    qbad2: 'Invitational Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 6,
    qowner: 'public',
    qkey: '1NT06',
    qdetail: 'After the following biddding.   1NT  P  3H.  What is your bid ?',
    qcorrect: 'Game force shortage in hearts',
    qbad1: 'Smolen 5 Spades, 4 Hearts',
    qbad2: 'Invitational in Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 7,
    qowner: 'public',
    qkey: '1NT07',
    qdetail: 'After the following biddding.   1NT  P  3S.  What is your bid ?',
    qcorrect: 'Game force shortage in Spades',
    qbad1: 'Smolen 5 Hearts 4 Spades',
    qbad2: 'Invitational in Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 8,
    qowner: 'public',
    qkey: '1NT08',
    qdetail:
      'After the following biddding.   1NT  P  2C  P,  2H  P  3S.  What is your bid ?',
    qcorrect: 'Confirming Hearts,  Start Cue bidding controls',
    qbad1: 'Has 6 spades and 4 hearts',
    qbad2: 'Smolen 5 Spades, 4 Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 9,
    qowner: 'public',
    qkey: '1NT09',
    qdetail:
      'After the following biddding.   1NT  P  2C  P,  2S  P  3H.  What is your bid ?',
    qcorrect: 'Confirming Spades  Start Cue bidding controls',
    qbad1: 'Has 6 Hearts and 4 Spades',
    qbad2: 'Smolen 4 Spades, 5 Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 10,
    qowner: 'public',
    qkey: '1NT10',
    qdetail:
      'After the following biddding.   1NT  P  2D  P,  2H  P  2S.  What is your bid ?',
    qcorrect: 'Showing 5 Hearts and 4 Spades invitational',
    qbad1: 'Garbage stayman, has heart shortage',
    qbad2: 'Garbage stayman, has Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 11,
    qowner: 'public',
    qkey: '1NT11',
    qdetail:
      'After the following biddding.   1NT  P  2S P, 2NT.  What is your bid ?',
    qcorrect: '3+ card Club support with honour',
    qbad1: 'Poor hand, to play',
    qbad2: 'Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 12,
    qowner: 'public',
    qkey: '1NT12',
    qdetail:
      'After the following biddding.   1NT  P  2S P, 3C.  What is your bid ?',
    qcorrect: 'Does not have 3+ card Club support with honour',
    qbad1: 'Has no honour in Clubs',
    qbad2: 'Forcing to 3NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 13,
    qowner: 'public',
    qkey: '1NT13',
    qdetail:
      'After the following biddding.   1NT  P  2NT P, 3C.  What is your bid ?',
    qcorrect: '3+ card Diamond support with honour',
    qbad1: 'Poor hand, to play in Clubs',
    qbad2: 'Invitational to 3NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 14,
    qowner: 'public',
    qkey: '1NT14',
    qdetail:
      'After the following biddding.   1NT  P  2S P, 3D.  What is your bid ?',
    qcorrect: 'Does not have 3+ card Diamond support with honour',
    qbad1: 'Has no honour in Diamond',
    qbad2: 'Forcing to 3NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 15,
    qowner: 'public',
    qkey: '1NT15',
    qdetail: 'After the following biddding.   1NT  P  3C.  What is your bid ?',
    qcorrect: 'Puppet Stayman',
    qbad1: 'Club Shortage',
    qbad2: 'Long clubs, Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 16,
    qowner: 'public',
    qkey: '1NT16',
    qdetail: 'After the following biddding.   1NT  P  3D.  What is your bid ?',
    qcorrect: 'Shortage in Diamonds, Game force',
    qbad1: 'Transfer to Hearts',
    qbad2: 'Long Diamonds, Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 17,
    qowner: 'public',
    qkey: '1NT17',
    qdetail: 'After the following biddding.   1NT  P  3H.  What is your bid ?',
    qcorrect: 'Shortage in Hearts Game force',
    qbad1: 'Transfer to Spades',
    qbad2: 'Long Hearts, Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 18,
    qowner: 'public',
    qkey: '1NT18',
    qdetail: 'After the following biddding.   1NT  P  3S.  What is your bid ?',
    qcorrect: 'Shortage in Spades, Game force',
    qbad1: 'Transfer to Minors',
    qbad2: 'Long Spades Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 19,
    qowner: 'public',
    qkey: '1NT19',
    qdetail: 'After the following biddding.   1NT   P  4D.  What is your bid ?',
    qcorrect: 'Texas Transfer to Hearts',
    qbad1: 'Long Diamonds, pre-emptive',
    qbad2: 'Long Diamonds, Invitational to 5D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 20,
    qowner: 'public',
    qkey: '1NT20',
    qdetail: 'After the following biddding.   1NT   P  4H.  What is your bid ?',
    qcorrect: 'Texas Transfer to Spades',
    qbad1: 'Long Hearts pre-emptive, weak',
    qbad2: 'Long Hearts, to Play',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 21,
    qowner: 'public',
    qkey: '1NT21',
    qdetail: 'After the following biddding.   1NT  P  4S.  What is your bid ?',
    qcorrect: 'To Play, no slam interest',
    qbad1: 'Texas Transfer to the minors',
    qbad2: 'Slam interest in Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 22,
    qowner: 'public',
    qkey: '1NT30',
    qdetail:
      'After the following biddding.   1NT P 3C P, 3NT.  What is your bid ?',
    qcorrect: 'No 4 or 5 card Major',
    qbad1: 'No club support',
    qbad2: 'No 3/4/5 card major',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 23,
    qowner: 'public',
    qkey: '1NT31',
    qdetail:
      'After the following biddding.   1NT  P  3C P, 3H.  What is your bid ?',
    qcorrect: '5 Hearts, Game Force',
    qbad1: 'Transfer to Spades',
    qbad2: '5 Hearts, Invitational',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 24,
    qowner: 'public',
    qkey: '1NT32',
    qdetail:
      'After the following biddding.   1NT  P  3C P, 3S.  What is your bid ?',
    qcorrect: '5 Spades, Game Force',
    qbad1: '6 Spades, Invitational',
    qbad2: '5 Spades, Invitational',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 25,
    qowner: 'public',
    qkey: '1NT33',
    qdetail:
      'After the following biddding.   1NT P 3C P, 3D P 3NT.  What is your bid ?',
    qcorrect: 'I have a 3 card Major, but no 4 card major',
    qbad1: 'I do not have diamonds',
    qbad2: 'I have clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 26,
    qowner: 'public',
    qkey: '1NT34',
    qdetail:
      'After the following biddding.   1NT  P  3C  P,  3D  P 3H.  What is your bid ?',
    qcorrect: 'I have 4 Spades, but not 4 hearts',
    qbad1: 'I have 4 Hearts',
    qbad2: 'I have 4 Spades and maybe 4 Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 27,
    qowner: 'public',
    qkey: '1NT35',
    qdetail:
      'After the following biddding.   1NT  P  3C  P,  3D  P 3S.  What is your bid ?',
    qcorrect: 'I have 4 Hearts, but not 4 Spades',
    qbad1: 'I have 4 Hearts and maybe 4 Spades',
    qbad2: 'I have 4 Hearts AND 4 Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 28,
    qowner: 'public',
    qkey: '1NT36',
    qdetail: 'After the following biddding.   1NT  P  3C.  What is your bid ?',
    qcorrect: 'I have AT LEAST one 3+ Card major',
    qbad1: 'I have EXACTLY one 4 card major',
    qbad2: 'I have AT LEAST one 4 card major',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 29,
    qowner: 'public',
    qkey: '1NT37',
    qdetail: 'After the following biddding.   1NT   P  3S.  What is your bid ?',
    qcorrect: 'I have exactly 5 Spades and 4 Hearts',
    qbad1: 'I have 5 spades EXACTLY, less than 3 hearts',
    qbad2: 'I have 5+ Spades, less than 3 hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 30,
    qowner: 'public',
    qkey: '1NT38',
    qdetail:
      'After the following biddding.   1NT  P  3C  P, 3D  P  4D.  What is your bid ?',
    qcorrect: 'I have BOTH majors',
    qbad1: 'I have long diamonds and long clubs',
    qbad2: 'I have BOTH Majors,  SLAM interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 31,
    qowner: 'public',
    qkey: '1NT39',
    qdetail: 'After the following biddding.   1NT  P  4C.  What is your bid ?',
    qcorrect: 'Gerber CRO',
    qbad1: 'Clubs invitational ',
    qbad2: 'Splinter in Clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 32,
    qowner: 'public',
    qkey: '1NT40',
    qdetail: 'After the following biddding.   1NT  P  4NT.  What is your bid ?',
    qcorrect: 'Quantitive Raise to 6NT',
    qbad1: 'Standard Ace Ask',
    qbad2: 'Quantitive Raise to 7NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 33,
    qowner: 'public',
    qkey: '1NT41',
    qdetail: 'After the following biddding.   1NT  P  5NT.  What is your bid ?',
    qcorrect: 'Quantitive Raise to 7NT',
    qbad1: 'Standard Ace Ask',
    qbad2: 'Quantitive Raise to 6NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 34,
    qowner: 'public',
    qkey: '1NT42',
    qdetail:
      'How do you bid after your partner shows 20-22 arriving at 2NT, if you hold 5 Spades and 4 Hearts ?',
    qcorrect: 'Bid 3S showing exacty 5 Spades and 4 Hearts',
    qbad1: 'Transfer to Spades and bid 4 hearts',
    qbad2: 'Puppet Stayman and on 3NT bid 4S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 35,
    qowner: 'public',
    qkey: '1NT43',
    qdetail:
      'How do you bid after your partner shows 20-22 arriving at 2NT, if you hold 5 Hearts and 4 Spades ?',
    qcorrect: 'Bid 3D transfer to Hearts and then 3S',
    qbad1: 'Transfer to Hearts and then bid 4S',
    qbad2: 'Transfer to Spades and bid 4 hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 36,
    qowner: 'public',
    qkey: '1NT44',
    qdetail:
      'How do you bid after your partner shows 20-22 arriving at 2NT, if you hold 5 Hearts and 5 Spades ?',
    qcorrect: 'Transfer to Spades and bid 4 Hearts',
    qbad1: 'Puppet Stayman',
    qbad2: 'Transfer to Hearts and bid 3S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 37,
    qowner: 'public',
    qkey: '1NT46',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT X.  What does this bidding sequence mean ?',
    qcorrect: 'Take out, at least 4/4 in both Majors and points for game',
    qbad1: 'Penalty, has the minors',
    qbad2: 'Stayman, has at least one major',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 38,
    qowner: 'public',
    qkey: '1NT47',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT 3C.  What does this bidding sequence mean ?',
    qcorrect: 'Puppet Stayman',
    qbad1: 'Standard Stayman',
    qbad2: 'Asking for a stopper in Clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 39,
    qowner: 'public',
    qkey: '1NT48',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT 3D.  What does this bidding sequence mean ?',
    qcorrect: 'Transfer to Hearts',
    qbad1: 'Invitational,  Diamonds',
    qbad2: 'Asking for a stopper in Diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 40,
    qowner: 'public',
    qkey: '1NT49',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT 3H.  What does this bidding sequence mean ?',
    qcorrect: 'Transfer to Spades',
    qbad1: 'Invitational, Hearts',
    qbad2: 'Asking for a stopper in Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 41,
    qowner: 'public',
    qkey: '1NT50',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT 3S.  What does this bidding sequence mean ?',
    qcorrect: 'Exactly 5/4 in Spades and Hearts',
    qbad1: 'Invitational, Spades',
    qbad2: 'Asking for a stopper in Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 42,
    qowner: 'public',
    qkey: '1NT51',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT 3H P, 3S P 4H.  What does this bidding sequence mean ?',
    qcorrect: 'Has 5/5 in the majors, you choose',
    qbad1: 'To play in Hearts',
    qbad2: 'Slam in Hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 43,
    qowner: 'public',
    qkey: '1NT52',
    qdetail:
      'Where 2NT shows 5/5 in the minors.   1NT  2NT 3NT.  What does this bidding sequence mean ?',
    qcorrect: 'To Play',
    qbad1: 'Both majors, you choose',
    qbad2: 'Strong, slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 44,
    qowner: 'public',
    qkey: '1NT53',
    qdetail:
      'After the following biddding.   1NT  P  2D  X,  P.  What is your bid ?',
    qcorrect: 'Exactly 2 hearts',
    qbad1: 'To play, likes diamonds',
    qbad2: 'Waiting bid',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 45,
    qowner: 'public',
    qkey: '1NT54',
    qdetail:
      'After the following biddding.   1NT  P  2D  X,  2H.  What is your bid ?',
    qcorrect: '3+ hearts',
    qbad1: 'Weak, 2+ hearts',
    qbad2: 'Strong, 2+ hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 46,
    qowner: 'public',
    qkey: '1NT55',
    qdetail:
      'After the following biddding.   1NT  P  2D  X,  XX.  What is your bid ?',
    qcorrect: 'To play in 2D',
    qbad1: 'SOS, weak and no heart support',
    qbad2: 'Heart support, take-out of diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 47,
    qowner: 'public',
    qkey: '1NT56',
    qdetail: 'After the following biddding.   1D 1NT P 2C.  What is your bid ?',
    qcorrect: 'To Play, weak SOS Rescue',
    qbad1: 'Stayman',
    qbad2: 'Helvic Wriggle',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 48,
    qowner: 'public',
    qkey: '1NT57',
    qdetail: 'After the following biddding.   1D 1NT P 2D.  What is your bid ?',
    qcorrect: 'To Play, weak SOS Rescue',
    qbad1: 'Transfer to Hearts',
    qbad2: 'Helvic Wriggle',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 49,
    qowner: 'public',
    qkey: '1NT58',
    qdetail: 'After the following biddding.   1D 1NT X 2C.  What is your bid ?',
    qcorrect: 'Helvic Wriggle',
    qbad1: 'Stayman',
    qbad2: 'To Play, weak SOS Rescue',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 50,
    qowner: 'public',
    qkey: '1NT59',
    qdetail: 'After the following biddding.   1D 1NT X XX.  What is your bid ?',
    qcorrect: 'Helvic Wriggle, partner must bid 2C',
    qbad1: 'Values redouble, penalty orientated',
    qbad2: 'SOS, bid lowest 4 card suit',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 51,
    qowner: 'public',
    qkey: '1NT60',
    qdetail:
      'After the following biddding.   1D 1NT X Pass.  What is your bid ?',
    qcorrect: 'Helvic Wriggle, partner must re-double',
    qbad1: 'To play.  Responder has values',
    qbad2: 'SOS, bid lowest 4 card suit',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 52,
    qowner: 'public',
    qkey: '1NT61',
    qdetail: 'After the following biddding.   1D 1NT X 2D.  What is your bid ?',
    qcorrect: 'Helvic Wriggle, shows Diamonds and Hearts',
    qbad1: '5 card Diamonds, to Play',
    qbad2: 'SOS, bid lowest 4 card suit',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 53,
    qowner: 'public',
    qkey: '1NT62',
    qdetail: 'After the following biddding.   1D 1NT P 3C.  What is your bid ?',
    qcorrect: 'Puppet Stayman.  Game force.',
    qbad1: 'Clubs to play',
    qbad2: 'Splinter in Clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 54,
    qowner: 'public',
    qkey: '1NT63',
    qdetail: 'After the following biddding.   1D 1NT X 3C.  What is your bid ?',
    qcorrect: 'Puppet Stayman.  Game force.',
    qbad1: 'Clubs to play',
    qbad2: 'Splinter in Clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 55,
    qowner: 'public',
    qkey: '1NT64',
    qdetail: 'After the following biddding.   1D 1NT X 3D.  What is your bid ?',
    qcorrect: 'Transfer to Hearts.  Game force.',
    qbad1: 'To play, Diamonds',
    qbad2: 'Transfer to Hearts.  Invitational',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 56,
    qowner: 'public',
    qkey: '1NT65',
    qdetail:
      'Opposition bid 2C (Clubs and another) over our 1NT.  Partner responds X..  What does this bidding sequence mean ?',
    qcorrect: 'Penalty.  Partner has good clubs and 8+ HCP',
    qbad1: 'Take out of Clubs',
    qbad2: 'Stayman',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 57,
    qowner: 'public',
    qkey: '1NT66',
    qdetail:
      'Opposition bid 2C (Clubs and another) over our 1NT.  Partner responds 2D..  What does this bidding sequence mean ?',
    qcorrect: 'Weak diamonds',
    qbad1: 'Transfer to hearts',
    qbad2: 'Helvic Wriggle',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 58,
    qowner: 'public',
    qkey: '1NT67',
    qdetail:
      'Opposition bid 2C (Clubs and another) over our 1NT.  Partner responds 2H..  What does this bidding sequence mean ?',
    qcorrect: 'Weak Hearts',
    qbad1: 'Transfer to spades',
    qbad2: 'Hearts and Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 59,
    qowner: 'public',
    qkey: '1NT68',
    qdetail:
      'Opposition bid 2C (Clubs and another) over our 1NT.  Partner responds 2NT.  What does this bidding sequence mean ?',
    qcorrect: 'Lebensohl.  Partner must bid 3C',
    qbad1: 'Invitational to 3NT, stop in clubs',
    qbad2: 'Transfer to Diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 60,
    qowner: 'public',
    qkey: '1NT69',
    qdetail:
      'Opposition bid 2C (Clubs and another) over our 1NT.  Partner responds 3H.  What does this bidding sequence mean ?',
    qcorrect: 'Invitational in hearts',
    qbad1: 'Transfer to Spades',
    qbad2: 'Game force in hearts',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 61,
    qowner: 'public',
    qkey: '1NT70',
    qdetail:
      'Opposition bid 2C (6 card suit) over our 1NT.  Partner responds 2NT.  What does this bidding sequence mean ?',
    qcorrect: 'Lebensohl.  Partner must bid 3C',
    qbad1: 'Invitational to 3NT, stop in clubs',
    qbad2: 'Transfer to Diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 62,
    qowner: 'public',
    qkey: '1NT71',
    qdetail:
      'After the following biddding.   1NT  2S (natural) 3S.  What does this bidding sequence mean ?',
    qcorrect: '4 card hearts, NO spade stopper',
    qbad1: 'Michaels, Hearts and a minor',
    qbad2: 'Asking for a Spade stopper',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 63,
    qowner: 'public',
    qkey: '1NT72',
    qdetail:
      'After the following biddding.   1NT  2S (natural)  2NT  P,  3C  P  3H.  What does this bidding sequence mean ?',
    qcorrect: 'Weak Hearts',
    qbad1: 'Transfer to Spades',
    qbad2: 'Asking for a Heart stopper',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 64,
    qowner: 'public',
    qkey: '1NT73',
    qdetail:
      'After the following biddding.   1NT  2S (natural)  2NT  P,  3C  P  3S.  What does this bidding sequence mean ?',
    qcorrect: '4 card hearts, WITH spade stopper',
    qbad1: 'Michaels, Hearts and a minor',
    qbad2: 'Showing a Spade stopper',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 65,
    qowner: 'public',
    qkey: '1NT74',
    qdetail:
      'After the following biddding.   1NT  2S (natural)  2NT  P,  3C  P  3NT.  What does this bidding sequence mean ?',
    qcorrect: 'Game values.  <4 Hearts.  No spade stopper',
    qbad1: 'Has stoppers in Hearts and Spades',
    qbad2: 'To play, long running minor',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 66,
    qowner: 'public',
    qkey: '1NT75',
    qdetail:
      'After the following biddding.   1NT  2S  3NT.  What does this bidding sequence mean ?',
    qcorrect:
      'Game values.  <4 Hearts.  To play, maybe a partial stopper in Spades',
    qbad1: 'Has stoppers in Hearts and Spades',
    qbad2: 'Has a stopper in Spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 67,
    qowner: 'public',
    qkey: '1NT76',
    qdetail:
      'Opposition bid 2C (Clubs stayman) over our 1NT.  Partner responds 2NT.  What does this bidding sequence mean ?',
    qcorrect: 'Lebensohl.  Partner must bid 3C',
    qbad1: 'Partner has both majors stopped, invitational.',
    qbad2: 'System on, Transfer to Diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 68,
    qowner: 'public',
    qkey: '1NT77',
    qdetail:
      'Opposition bid 2C (Clubs stayman) over our 1NT.  Partner responds X.  What does this bidding sequence mean ?',
    qcorrect: 'Penalty, Values Double',
    qbad1: 'Invitational to 3NT, both majors stopped',
    qbad2: 'Partner has long Clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 69,
    qowner: 'public',
    qkey: '1NT78',
    qdetail:
      'Opposition bid 2C (Clubs stayman) over our 1NT.  1NT  2C  3C.  What does this bidding sequence mean ?',
    qcorrect: 'Strong clubs.  Invitational',
    qbad1: 'Weak Clubs',
    qbad2: 'Pre-emptive in Clubs',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 70,
    qowner: 'public',
    qkey: '1NT79',
    qdetail:
      'After 1NT  P  2D  X, what would you bid holding the following KQx,xx,KQJTx,AQx ?',
    qcorrect: 'Redouble',
    qbad1: '2H',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 71,
    qowner: 'public',
    qkey: '1NT80',
    qdetail:
      'After 1NT  P  2D  X, what would you bid holding the following KQJx,Ax,Jxxx,AQx ?',
    qcorrect: 'Pass',
    qbad1: '2H',
    qbad2: 'Redouble',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 72,
    qowner: 'public',
    qkey: '1NT81',
    qdetail:
      'After 1NT  P  2D  X, what would you bid holding the following KQx,Qxx,KJTx,AQx ?',
    qcorrect: '2H',
    qbad1: 'Redouble',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: '1NT',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 157,
    qowner: 'public',
    qkey: 'PS16',
    qdetail:
      'Your LHO opens 1C which is passed around to you holding KQ4,AJ7,9762,KQJ ?',
    qcorrect: 'Double',
    qbad1: '1NT',
    qbad2: '1D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 73,
    qowner: 'public',
    qkey: 'Double01',
    qdetail:
      'After the following biddding.   1D  P  1H  1S,  X.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit',
    qbad1: '4+ clubs',
    qbad2: 'Heart stopper',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/support_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 74,
    qowner: 'public',
    qkey: 'Double02',
    qdetail:
      'After the following biddding.   1D  1H  1S  2C,  X.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit',
    qbad1: 'Penalty double',
    qbad2: 'Asking for a club stopper',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/support_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 75,
    qowner: 'public',
    qkey: 'Double03',
    qdetail:
      'After the following biddding.   1C  1D  1H  2D, X.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit',
    qbad1: 'Penalty double',
    qbad2: 'Takeout, has 4 spades',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/support_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 76,
    qowner: 'public',
    qkey: 'Double04',
    qdetail:
      'After the following biddding.   1H  P  1S  X,  XX.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit',
    qbad1: 'Take out, has clubs and diamonds',
    qbad2: 'Penalty, subsequent doubles are also penalty',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/support_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 77,
    qowner: 'public',
    qkey: 'Double05',
    qdetail:
      'After the following biddding.   1D  P  1H  1S,  2C  How many hearts does opener have ?',
    qcorrect: 'Less than 3 hearts',
    qbad1: '3 or fewer',
    qbad2: 'Undetermined',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/support-doubles ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 78,
    qowner: 'public',
    qkey: 'Double06',
    qdetail:
      'After the following biddding.   1D  P  1S  3C,  X.  What does this bidding sequence mean ?',
    qcorrect: 'Penalty Double',
    qbad1: '3 card support of partners suit',
    qbad2: 'Takeout, has diamonds and hearts',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/support-doubles ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 79,
    qowner: 'public',
    qkey: 'Double07',
    qdetail:
      'After the following biddding.   1D  P  1S  2H,  X.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit',
    qbad1: '5+ Diamonds, 4 clubs',
    qbad2: 'Penalty, subsequent doubles are also penalty',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/support-doubles ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 80,
    qowner: 'public',
    qkey: 'Double08',
    qdetail:
      'After the following biddding.   1D  P  1S  3C,  P  X.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit & extra values',
    qbad1: 'Penalty double',
    qbad2: 'Take out',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/support-doubles ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 81,
    qowner: 'public',
    qkey: 'Double09',
    qdetail:
      'After the following biddding.   1D  1H  1S  2C,  X.  What does this bidding sequence mean ?',
    qcorrect: '3 card support of partners suit',
    qbad1: 'Penalty, has clubs',
    qbad2: 'Flat 10+ HCP',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/support-doubles ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 82,
    qowner: 'public',
    qkey: 'Double10',
    qdetail:
      'After the following biddding.   1C  1D  X.  What does this bidding sequence mean ?',
    qcorrect: '4H+, 4S+, 6+ points',
    qbad1: 'At least one 4+ card major and a 3+ card',
    qbad2: 'Shows NO stopper in Diamonds, 6-9 HCP, no 4 card major',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 83,
    qowner: 'public',
    qkey: 'Double11',
    qdetail:
      'After the following biddding.   1H  1S  X.  What does this bidding sequence mean ?',
    qcorrect: '4C+, 4D+, 6+ points',
    qbad1: 'Support double of Hearts',
    qbad2: 'Has both Minors and 10+ HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 84,
    qowner: 'public',
    qkey: 'Double12',
    qdetail:
      'After the following biddding.   1D  2C  X.  What does this bidding sequence mean ?',
    qcorrect: 'At least one 4 card major',
    qbad1: 'Both Majors, 4+ cards',
    qbad2: '10+ HCP, no diamond support',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 85,
    qowner: 'public',
    qkey: 'Double13',
    qdetail:
      'After the following biddding.   1D  1H  X  P,  1S.  What does this bidding sequence mean ?',
    qcorrect: 'Opener 4S (sometimes 3), 11-14 HCP',
    qbad1: 'Exactly 3 spades support',
    qbad2: 'Exactly 4 card spades support',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 86,
    qowner: 'public',
    qkey: 'Double14',
    qdetail:
      'After the following biddding.   1D  1H  X  P,  2S.  What does this bidding sequence mean ?',
    qcorrect: 'Opener 4S, 15-16 HCP',
    qbad1: 'Pre-empt, 4 card spades and 11-14 HCP',
    qbad2: 'Pre-empt, 3 card spades and 11-14 HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 87,
    qowner: 'public',
    qkey: 'Double15',
    qdetail:
      'After the following biddding.   1D  1H  X  P,  3S.  What does this bidding sequence mean ?',
    qcorrect: 'Opener 4S, 17-18 HCP',
    qbad1: 'Pre-empt, 4 card spades and 11-14 HCP',
    qbad2: '4 card spades and 15-16 HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 88,
    qowner: 'public',
    qkey: 'Double16',
    qdetail:
      'After the following biddding.   1D  1H  X  P,  4S.  What does this bidding sequence mean ?',
    qcorrect: 'Opener 4S, 19-21 HCP',
    qbad1: '4 card spades and 15-16 HCP',
    qbad2: '4 card spades and 17-18 HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 89,
    qowner: 'public',
    qkey: 'Double17',
    qdetail:
      'After the following biddding.   1D  1S  X  P,  1NT.  What does this bidding sequence mean ?',
    qcorrect: 'Opener <4H, Spade stopper, 12-14 HCP',
    qbad1: 'Weak, <3 hearts',
    qbad2: 'Opener <4 Hearts, 12-14 HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 90,
    qowner: 'public',
    qkey: 'Double18',
    qdetail:
      'After the following biddding.   1D  1S  X  P,  2NT.  What does this bidding sequence mean ?',
    qcorrect: 'Opener <4H, Spade stopper, 18-19 HCP',
    qbad1: 'Opener <3H, Spade stopper, 16+ HCP',
    qbad2: 'Opener <4H, Spade stopper, 15-17 HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 91,
    qowner: 'public',
    qkey: 'Double19',
    qdetail:
      'After the following biddding.   1C  1S  X  P,  2C.  What does this bidding sequence mean ?',
    qcorrect: 'Opener 6C+, 11-15 HCP',
    qbad1: 'Opener has no spade stopper, 5+ clubs',
    qbad2: 'Opener has 5+ clubs, <4H, <4D',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 92,
    qowner: 'public',
    qkey: 'Double20',
    qdetail:
      'After the following biddding.   1C  1S  X  P,  3C.  What does this bidding sequence mean ?',
    qcorrect: 'Opener 6C+, 16-19 HCP',
    qbad1: 'Opener has 7C+, 11-14 HCP',
    qbad2: 'Opener has 6C+,  <3H, <3S',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 93,
    qowner: 'public',
    qkey: 'Double21',
    qdetail:
      'After the following biddding.   1D  1H  X  P,  2H.  What does this bidding sequence mean ?',
    qcorrect: '16+ HCP, 3S',
    qbad1: 'Exactly 3 spades support',
    qbad2: '16+ HCP, 4S',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 94,
    qowner: 'public',
    qkey: 'Double22',
    qdetail:
      'After the following biddding.   1D  P  1NT  X.  What does this bidding sequence mean ?',
    qcorrect: 'Take-out.  Asks partner to bid Clubs, Hearts or Spades',
    qbad1: 'Penalty.  16+ HCP',
    qbad2: 'Take-out.  Has both majors',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/takeout_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 95,
    qowner: 'public',
    qkey: 'Double23',
    qdetail:
      'After the following biddding.   1C  P  P  X,  P  1H  P  1S.  What does this bidding sequence mean ?',
    qcorrect: '1S shows 5S+,  16+ HCP',
    qbad1: '1S shows no support for Hearts, weak',
    qbad2: '1S shows 4S and 3H, weak',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/takeout_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 96,
    qowner: 'public',
    qkey: 'Double24',
    qdetail:
      'After the following biddding.   1S  P  2S  P, X.  What does this bidding sequence mean ?',
    qcorrect: 'Takout double',
    qbad1: 'Penalty double',
    qbad2: '4 Hearts, 3+ of other suots',
    qbad3: null,
    qhl1: 'https://www.andrewrobson.co.uk/article/tips_for_intermediates/1765 ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 97,
    qowner: 'public',
    qkey: 'Double25',
    qdetail:
      'After the following biddding.   1S  P  2S  P,  3S  P  4S  X.  What does this bidding sequence mean ?',
    qcorrect: 'Penalty Double',
    qbad1: 'Take Out Double',
    qbad2: 'Lead directing double',
    qbad3: null,
    qhl1: 'https://www.andrewrobson.co.uk/article/tips_for_intermediates/1765 ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 98,
    qowner: 'public',
    qkey: 'Double26',
    qdetail:
      'After the following biddding.   1NT  X.  What does this bidding sequence mean ?',
    qcorrect: 'Penalty Double',
    qbad1: 'Take Out Double',
    qbad2: 'Snapdragon Double',
    qbad3: null,
    qhl1: 'https://www.andrewrobson.co.uk/article/tips_for_intermediates/1765 ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 99,
    qowner: 'public',
    qkey: 'Double27',
    qdetail:
      'After the following biddding.   1H  P  1NT  X.  What does this bidding sequence mean ?',
    qcorrect: 'Takout double',
    qbad1: 'Penalty Double',
    qbad2: '2 suiter 5/5',
    qbad3: null,
    qhl1: 'https://www.andrewrobson.co.uk/article/tips_for_intermediates/1765 ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 158,
    qowner: 'public',
    qkey: 'PS17',
    qdetail:
      'Your LHO opens 1C which is passed around to you holding AKJT74,KJ4,75,63 ?',
    qcorrect: '2S',
    qbad1: '1S',
    qbad2: '3S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 100,
    qowner: 'public',
    qkey: 'Double28',
    qdetail:
      'After the following biddding.   1NT  X  2D  X.  What does this bidding sequence mean ?',
    qcorrect: 'Penalty Double',
    qbad1: 'Takout double',
    qbad2: 'Lead directing double',
    qbad3: null,
    qhl1: 'https://www.andrewrobson.co.uk/article/tips_for_intermediates/1765 ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 101,
    qowner: 'public',
    qkey: 'Double29',
    qdetail:
      'After the following biddding.   1D  X  2D  X.  What does this bidding sequence mean ?',
    qcorrect: 'Responsive Double.  Showing 4+ in the Majors',
    qbad1: 'Take Out, Flat hand at least 3 in each suit.  You choose partner',
    qbad2: 'Penalty, 10+ HCP',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/responsive_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 102,
    qowner: 'public',
    qkey: 'Double30',
    qdetail:
      'After the following biddding.   1H  X  2H  X ?.  What does this bidding sequence mean ?',
    qcorrect: 'Responsive Double.  Showing 4+ in the Minors',
    qbad1: 'Take Out, Flat hand at least 3 in each suit.  You choose partner',
    qbad2: '4 Spades',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/responsive_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 103,
    qowner: 'public',
    qkey: 'Double31',
    qdetail: '1H  X  2H  You hold  K964,5,KT53,A984, what do you bid ?',
    qcorrect: '2S .  Support partner',
    qbad1: 'X.  Take-out double for the other 3 suits',
    qbad2: 'X.  Responsive double showing the minors',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/responsive_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 104,
    qowner: 'public',
    qkey: 'Double32',
    qdetail: 'How many HCP are required for a responsive double ? ',
    qcorrect:
      '6+ points at the 2-level, 8+ points at the 3-level, 10+ points at the 4-level',
    qbad1: 'No Minimum Level',
    qbad2:
      '10+ points at the 2-level, 12+ points at the 3-level, 14+ points at the 4-level',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/responsive_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 105,
    qowner: 'public',
    qkey: 'Double33',
    qdetail:
      'After the following biddding.   1S  2H  2S  X.  What does this bidding sequence mean ?',
    qcorrect: 'Denying heart support but promising both minors',
    qbad1: '3 card support of partners suit',
    qbad2: '10+ HCP, flat hand',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/responsive_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 106,
    qowner: 'public',
    qkey: 'Double34',
    qdetail: 'Which is a responsive Double ?',
    qcorrect: '1H  X  2H  X',
    qbad1: '1C  X  1S  X',
    qbad2: '1C  2S  3C  X',
    qbad3: null,
    qhl1: 'http://www.bridgeguys.com/doubles/ResponsiveDouble.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 107,
    qowner: 'public',
    qkey: 'Double35',
    qdetail:
      'What should you bid with 8HCP and 4513 distribution after the following bidding,  1D  X  2D ?',
    qcorrect: '2H',
    qbad1: 'Double',
    qbad2: '3D',
    qbad3: null,
    qhl1: 'http://www.bridgeguys.com/doubles/ResponsiveDouble.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 108,
    qowner: 'public',
    qkey: 'Double36',
    qdetail:
      'You hold 873,72,QJT7,QJT5.  Bidding goes 1H  X  2H, what should you bid ?',
    qcorrect: 'Responsive double showing the minors',
    qbad1: 'Support double showing 3 spades',
    qbad2: 'Pass, too weak',
    qbad3: null,
    qhl1: 'http://www.bridgeguys.com/doubles/ResponsiveDouble.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 109,
    qowner: 'public',
    qkey: 'Double37',
    qdetail:
      'You hold QJ987,QJT987,void,7.  Bidding goes 1D  X  2D, what should you bid ?',
    qcorrect: '3D Cue bid showing BOTH Majors',
    qbad1: 'Responsive Double showing BOTH majors',
    qbad2: '2S planning to bid 3/4H next bid',
    qbad3: null,
    qhl1: 'http://www.bridgeguys.com/doubles/ResponsiveDouble.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 110,
    qowner: 'public',
    qkey: 'Double38',
    qdetail:
      'You hold 32,K732,Q5,KQJT3.  Bidding goes P,  1D  1S  3D (pre-emptive), what should you bid ?',
    qcorrect: 'Double showing the other two suits',
    qbad1: '3H  Always bid the Major first',
    qbad2: '4C  Always bid the longest suit',
    qbad3: null,
    qhl1: 'http://www.bridgeguys.com/doubles/ResponsiveDouble.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 111,
    qowner: 'public',
    qkey: 'Double39',
    qdetail:
      'What should you bid holding 543, 653, AT9876, void after the bidding goes 1H   P  2C  P ,  3H  P  6H  ?',
    qcorrect: 'Double',
    qbad1: 'Pass',
    qbad2: '7D',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/lightner_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 112,
    qowner: 'public',
    qkey: 'Double40',
    qdetail:
      'What should you bid holding 762,void,AT987,K9876 after the bidding goes 1S  3C  3S  5C, 6S  P  P ?',
    qcorrect: 'Double',
    qbad1: 'Pass',
    qbad2: '7C',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/lightner_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 113,
    qowner: 'public',
    qkey: 'Double41',
    qdetail:
      'What should you bid holding A762,void,76,T876543 after the bidding goes 1D  P  3D  P,  4NT  P  5D  P,  6D ?',
    qcorrect: 'Double',
    qbad1: 'Pass',
    qbad2: '7C',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/lightner_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 114,
    qowner: 'public',
    qkey: 'Double51',
    qdetail: 'What do you bid holding A86,95,AKJ86,K42 after 1H  2D ?',
    qcorrect: 'Pass',
    qbad1: '2NT',
    qbad2: 'Double',
    qbad3: null,
    qhl1: 'http://bridgemedley.blogspot.com/2012/12/reopening-doubles.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 115,
    qowner: 'public',
    qkey: 'Double52',
    qdetail: 'What do you bid holding J5,AQT864,8,AQT8 after 1H  2D  P  P,  ?',
    qcorrect: '2H',
    qbad1: 'Pass',
    qbad2: 'Double',
    qbad3: null,
    qhl1: 'http://bridgemedley.blogspot.com/2012/12/reopening-doubles.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 116,
    qowner: 'public',
    qkey: 'Double53',
    qdetail: 'What do you bid holding J75,AKT864,8,AK9 after 1H  2D ?',
    qcorrect: 'Double',
    qbad1: '2H',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: 'http://bridgemedley.blogspot.com/2012/12/reopening-doubles.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 117,
    qowner: 'public',
    qkey: 'Double54',
    qdetail:
      'After the following biddding.   1S  X  2S.  What does this bidding sequence mean ?',
    qcorrect: 'Simple raise, can be pre-emptive 3-9 HCP',
    qbad1: 'Simple raise, 2 Spades, pre-emptive',
    qbad2: 'Bergen Raise.  3 Spades 6-9 HCP',
    qbad3: null,
    qhl1: '1M Bergen Raises',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 118,
    qowner: 'public',
    qkey: 'Double55',
    qdetail: 'A Support Double is ?',
    qcorrect:
      'Opener shows EXACTLY 3 card support of Responders suit after opposition interference',
    qbad1:
      'Opener/Responder shows EXACTLY 3 card support of Responders/Openers suit after opposition interference',
    qbad2:
      'Opener shows 3 or MORE card support of Responders suit after opposition interference',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/support_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 119,
    qowner: 'public',
    qkey: 'Double56',
    qdetail: 'A Negative Double is ?',
    qcorrect:
      'Responder shows 6+ HCP and at least one 4 card suit in the unbid suits, usually the Major',
    qbad1: 'Responder shows EXACTLY 4 cards in the unbid major',
    qbad2: 'Responder shows 10+ HCP and at least 3 cards in the unbid suits',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/negative_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 120,
    qowner: 'public',
    qkey: 'Double57',
    qdetail: 'A Takeout Double is ?',
    qcorrect:
      'The takeout double is a double by OPENER that asks partner to bid one of the unbid suits. The double usually shows 11+ points and 3+ cards in each unbid suit.',
    qbad1:
      'The takeout double is a double by OPENER or RESPONDER that asks partner to bid one of the unbid suits.',
    qbad2:
      'A takeout double is by Opener when there is interference by opposition',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/takeout_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 121,
    qowner: 'public',
    qkey: 'Double58',
    qdetail: 'A Responsive Double is ?',
    qcorrect:
      'A Responsive double is used after partner makes a takeout double to show 4-4 shape in the Minor or Major suits',
    qbad1:
      'A Responsive double is used after partner makes a takeout double to show at least 3 cards in each of the unbid suits',
    qbad2:
      'A Responsive double is used after partner passes to show at least 3 cards in each of the unbid suits',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/responsive_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 122,
    qowner: 'public',
    qkey: 'Double59',
    qdetail: 'A Lightner Double is ?',
    qcorrect:
      'A Lead-directing double asking parter to make an unusual lead, and NOT to lead any suit bid on our side',
    qbad1: 'A Lead-directing double asking parter to lead TRUMPS',
    qbad2:
      'A penalty double when the opponents are in Slam asking partner to lead any Ace or King he has',
    qbad3: null,
    qhl1: 'http://www.bridgebum.com/lightner_double.php ',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 123,
    qowner: 'public',
    qkey: 'Double62',
    qdetail: 'A Reopening Double is ?',
    qcorrect:
      'A double to protect against partner having the opponents suit.  No extra values promised, but no more than two cards in the overcallers suit.',
    qbad1: 'A double promising extra values in pass out seat',
    qbad2: 'A double promising a shortage in overcallers suit and extra values',
    qbad3: null,
    qhl1: 'http://bridgemedley.blogspot.com/2012/12/reopening-doubles.html',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 124,
    qowner: 'public',
    qkey: 'Double63',
    qdetail: '1NT  P  2C  X',
    qcorrect:
      'Lead directing, partner has Clubs - At least a 5 card suit with 3 of the top 5 honours',
    qbad1: 'Penalty, partner has both Majors',
    qbad2:
      'Lead directing, partner has a strong hand and at least AKJ in clubs',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/lead-directing-doubles',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 159,
    qowner: 'public',
    qkey: 'PS18',
    qdetail:
      'The auction proceeds 1H  2S  3S  what do you bid holding K4,842,98753,A84 ?',
    qcorrect: 'Double',
    qbad1: 'Pass',
    qbad2: '3S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 160,
    qowner: 'public',
    qkey: 'PS19',
    qdetail:
      'The auction proceeds 1H  2S  3S  what do you bid holding K764,76,A9873,76 ?',
    qcorrect: '4S',
    qbad1: 'Double',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 125,
    qowner: 'public',
    qkey: 'Double64',
    qdetail:
      'A Lead directing double is ?.  What does this bidding sequence mean ?',
    qcorrect:
      'A double asking partner to lead a certain suit which opponents have bid when they end up in the final contract',
    qbad1:
      'A double demanding a certain suit is lead as opening lead.  Partner is not allowed to lead any alternative',
    qbad2:
      'A double to show length in a suit and asking partner to sacrifice on their bid if they have support',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/lead-directing-doubles',
    qhl2: null,
    qgroup1: 'Doubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 126,
    qowner: 'public',
    qkey: 'Redouble01',
    qdetail:
      'After the following biddding.   1C  X  XX.  What does this bidding sequence mean ?',
    qcorrect:
      'VALUES Responder Redouble.  10+ HCP, subsequent doubles are penalty',
    qbad1: 'SUPPORT Double, 3 card fit, 6 + HCP',
    qbad2: 'RESCUE re-double (SOS)',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 127,
    qowner: 'public',
    qkey: 'Redouble02',
    qdetail:
      'After the following biddding.   1H  X  XX.  What does this bidding sequence mean ?',
    qcorrect:
      'VALUES Responder Redouble.  10+ HCP, subsequent doubles are penalty',
    qbad1: 'SNAPDRAGON re-double',
    qbad2: 'RESCUE re-double (SOS)',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 128,
    qowner: 'public',
    qkey: 'Redouble03',
    qdetail:
      'After the following biddding.   1C  P  1H   X,   XX.  What does this bidding sequence mean ?',
    qcorrect:
      "SUPPORT re-double.  3 card support of partners suit, after partner's 1 of a major",
    qbad1: 'GAME FORCE re-double',
    qbad2: 'TAKE-OUT re-double',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 129,
    qowner: 'public',
    qkey: 'Redouble04',
    qdetail:
      'After the following biddding.   1C 1S  2H  X,  XX.  What does this bidding sequence mean ?',
    qcorrect: 'VALUES redouble from opener',
    qbad1: 'SUPPORT re-double.  3 card support of partners suit, 1 of a major',
    qbad2: 'RESCUE re-double (SOS)',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 130,
    qowner: 'public',
    qkey: 'Redouble05',
    qdetail:
      'After the following biddding.   1C  P  P  X,  P  P  XX.  What does this bidding sequence mean ?',
    qcorrect: 'RESCUE re-double (SOS)',
    qbad1: 'SUPPORT Double, 3 card fit, 6 + HCP',
    qbad2: 'SUPPORT 4 card fit for clubs',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 131,
    qowner: 'public',
    qkey: 'Redouble06',
    qdetail:
      'After the following biddding.   1NT  P  P  X,  P  P  XX.  What does this bidding sequence mean ?',
    qcorrect: 'Bid lowest 4 card suit, try to escape 1NT XX',
    qbad1: 'HELVIC Wriggle',
    qbad2: 'PENALTY double',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 132,
    qowner: 'public',
    qkey: 'Redouble07',
    qdetail:
      'After the following biddding.   4S  X  XX.  What does this bidding sequence mean ?',
    qcorrect: 'PENALTY, To play, subsequent doubles penalty',
    qbad1: 'SLAM INVITATION, responder has a big hand',
    qbad2: 'TAKE-OUT responder wants you to bid your best suit',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 133,
    qowner: 'public',
    qkey: 'Redouble08',
    qdetail:
      'After the following biddding.   2S  X  XX.  What does this bidding sequence mean ?',
    qcorrect: 'PENALTY, To play, subsequent doubles penalty',
    qbad1: 'TAKE OUT, responder is looking for 3NT',
    qbad2: 'TAKE-OUT responder wants you to bid your best suit',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 134,
    qowner: 'public',
    qkey: 'Redouble09',
    qdetail:
      'After the following biddding.   2S  X  2NT  3H,   P  P  X.  What does this bidding sequence mean ?',
    qcorrect: 'PENALTY, To play, subsequent doubles penalty',
    qbad1: 'TAKE OUT, responder is looking for 3NT',
    qbad2: 'TAKE-OUT responder wants you to bid your best suit',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 135,
    qowner: 'public',
    qkey: 'Redouble10',
    qdetail:
      'After the following biddding.   2S  X  XX  3C,  X.  What does this bidding sequence mean ?',
    qcorrect: 'PENALTY, To play, subsequent doubles penalty',
    qbad1: 'TAKE OUT, opener has no stops in clubs',
    qbad2: 'Opener has extra spade length but is weak',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 136,
    qowner: 'public',
    qkey: 'Redouble11',
    qdetail:
      'After the following biddding.   2S  X  XX  3C, Pass.  What does this bidding sequence mean ?',
    qcorrect: "CAN'T PENALTY.  Opener has no defensive tricks.",
    qbad1: 'TRAP PASS - Opener is waiting for responder to double',
    qbad2: 'Opener likes clubs and wishes to defend',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 137,
    qowner: 'public',
    qkey: 'Redouble12',
    qdetail:
      'After the following biddding.   2S  X  XX  3H,  P  P  X.  What does this bidding sequence mean ?',
    qcorrect: 'PENALTY.  Responder has values to defeat contract',
    qbad1: 'TAKE OUT.  Responder is two suited in the minors',
    qbad2: 'STOPPER ASK - Responder is looking to play in 3NT',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 138,
    qowner: 'public',
    qkey: 'Redouble13',
    qdetail:
      'After the following biddding.   1NT  P  2C  X,  XX.  What does this bidding sequence mean ?',
    qcorrect: 'TO PLAY in 2C',
    qbad1: 'I have BOTH majors, you choose, game force',
    qbad2:
      'I have NEITHER major, you choose what to do.  I will pass your response.',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 139,
    qowner: 'public',
    qkey: 'Redouble14',
    qdetail:
      'We are looking to bid 3NT with a cue bid of their suit at the 3 level as a stopper ask.  They double and we redouble.  For 3X  X  XX.  What does this bidding sequence mean ?',
    qcorrect: 'I have a partial stopper',
    qbad1: 'I have 1 stopper',
    qbad2: 'I have 2 stoppers',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 140,
    qowner: 'public',
    qkey: 'Redouble15',
    qdetail:
      'We are looking to bid 3NT with a cue bid of their suit at the 3 level as a stopper ask.  They double and we bid 3NT..  What does this bidding sequence mean ?',
    qcorrect: 'I have a 1+ stoppers',
    qbad1: 'I have exactly 1 stopper',
    qbad2: 'I have exactly 2 stoppers',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 141,
    qowner: 'public',
    qkey: 'Redouble16',
    qdetail:
      '1H  P  3D  P,  3S  X  P  P,  XX.  What does this bidding sequence mean ?',
    qcorrect: 'First round control in Spades, Ace/Void in bid suit',
    qbad1: 'King of Spades',
    qbad2: 'Asking for a stopper to get to 3NT',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=5NCyGSLk_y4',
    qhl2: null,
    qgroup1: 'Redoubles',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 142,
    qowner: 'public',
    qkey: 'PS01',
    qdetail: 'What do you bid holding 86,AQ73,6,KJT762 ?',
    qcorrect: '1C',
    qbad1: 'Pass',
    qbad2: '3C',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 143,
    qowner: 'public',
    qkey: 'PS02',
    qdetail: 'What do you bid holding 6,763,K86,KJT942 ?',
    qcorrect: '3C',
    qbad1: 'Pass',
    qbad2: '1C',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 144,
    qowner: 'public',
    qkey: 'PS03',
    qdetail: 'What do you bid holding AQ,J43,Q765,KQT3 ?',
    qcorrect: '1C',
    qbad1: '1D',
    qbad2: '1NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 145,
    qowner: 'public',
    qkey: 'PS04',
    qdetail:
      'What do you bid after 1H  P  1S  P, 2C  P holding K743,52,AJT84,T4 ?',
    qcorrect: '2H',
    qbad1: '2D',
    qbad2: '2NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 146,
    qowner: 'public',
    qkey: 'PS05',
    qdetail:
      'What do you bid after 1H  P  1S  P, 2C  P holding AQ742,A5,973,K86 ?',
    qcorrect: '2D',
    qbad1: '2S',
    qbad2: '2NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 147,
    qowner: 'public',
    qkey: 'PS06',
    qdetail: 'What do you bid after 1S X holding Q832,76,94,T9865 ?',
    qcorrect: '3S',
    qbad1: '2S',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 148,
    qowner: 'public',
    qkey: 'PS07',
    qdetail: 'What do you bid after 1S X holding 9,Q753,K94,AQJ53 ?',
    qcorrect: 'Redouble',
    qbad1: '2C',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 149,
    qowner: 'public',
    qkey: 'PS08',
    qdetail: 'What do you bid after 1S X holding AT97,AQ5.9753,T9 ?',
    qcorrect: '3D',
    qbad1: '2NT',
    qbad2: '3S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 150,
    qowner: 'public',
    qkey: 'PS09',
    qdetail: 'What do you bid after 1NT  P   holding 74,85,K92,AQJ753 ?',
    qcorrect: '3NT',
    qbad1: '2S',
    qbad2: '4C',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 151,
    qowner: 'public',
    qkey: 'PS10',
    qdetail: 'What do you bid after 1NT  P  holding J765,9864,QT63,5 ?',
    qcorrect: '2C',
    qbad1: 'Pass',
    qbad2: '2D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 152,
    qowner: 'public',
    qkey: 'PS11',
    qdetail: 'What do you bid after 1H  1NT holding 984,7,KQJ743,987 ?',
    qcorrect: '2D',
    qbad1: 'Pass',
    qbad2: 'Double',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 153,
    qowner: 'public',
    qkey: 'PS12',
    qdetail: 'What do you bid after 1H  1NT holding KT,K9,A8765,9753 ?',
    qcorrect: 'Double',
    qbad1: '2D',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 154,
    qowner: 'public',
    qkey: 'PS13',
    qdetail: 'What do you bid after 1D from RHO holding 4,A9863,AK7,AK98 ?',
    qcorrect: '1H',
    qbad1: 'Double',
    qbad2: '1NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 155,
    qowner: 'public',
    qkey: 'PS14',
    qdetail: 'What do you bid after 1D from RHO holding K76,AQ7,53,A8743 ?',
    qcorrect: 'Double',
    qbad1: '2C',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 156,
    qowner: 'public',
    qkey: 'PS15',
    qdetail: 'What do you bid after 1D from RHO holding AQJ6,96,AQ9,9853 ?',
    qcorrect: '1S',
    qbad1: '1NT',
    qbad2: 'Double',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Points Schmoints',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 161,
    qowner: 'Richard',
    qkey: 'System01',
    qdetail:
      'After the following biddding.   2NT 3S.  What does this bidding sequence mean ?',
    qcorrect: 'Responser has 5 spades and 4 hearts',
    qbad1: 'Transfer to Minors',
    qbad2: 'Responder is weak, stop in 3S',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 162,
    qowner: 'Richard',
    qkey: 'System02',
    qdetail:
      'After the following biddding.   1C  P  2D.  What does this bidding sequence mean ?',
    qcorrect: 'Drop dead.  6 card suit, weak',
    qbad1: 'Bergen Raise',
    qbad2: 'Strong  game force',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 163,
    qowner: 'Richard',
    qkey: 'System03',
    qdetail:
      'After the following biddding.   1C 1D 2H.  What does this bidding sequence mean ?',
    qcorrect: 'Drop dead.  6 card suit, weak',
    qbad1: 'Bergen Raise',
    qbad2: 'Strong  game force',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 164,
    qowner: 'Richard',
    qkey: 'System04',
    qdetail:
      'After the following biddding.   1C  X  2S.  What does this bidding sequence mean ?',
    qcorrect: 'Drop dead.  6 card suit, weak',
    qbad1: 'Bergen Raise',
    qbad2: 'Strong  game force',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 165,
    qowner: 'Richard',
    qkey: 'System05',
    qdetail:
      'After the following biddding.   1D  1S  2H.  What does this bidding sequence mean ?',
    qcorrect: '5 card suit and 10+ points',
    qbad1: 'Drop dead.  6 card suit, weak',
    qbad2: 'Strong  game force',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 166,
    qowner: 'Richard',
    qkey: 'System06',
    qdetail:
      'After the following biddding.   1D  X  2D.  What does this bidding sequence mean ?',
    qcorrect: 'Inverted Minors, Game force',
    qbad1: 'Weak 4 diamonds 6-9 points',
    qbad2: 'Check Back',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/inverted-minors',
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 167,
    qowner: 'Richard',
    qkey: 'System07',
    qdetail:
      'After the following biddding.   1D  X  3D.  What does this bidding sequence mean ?',
    qcorrect: 'Inverted Minors, Weak, 5 Diamonds',
    qbad1: 'Strong diamonds, Game force',
    qbad2: 'Standard Psyche',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/inverted-minors',
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 168,
    qowner: 'Richard',
    qkey: 'System08',
    qdetail:
      'After the following biddding.   1C  P  2C.  What does this bidding sequence mean ?',
    qcorrect: 'Inverted Minors, Game force',
    qbad1: 'Weak 5 clubs 6-9 points',
    qbad2: 'Weak 6 clubs 6-9 HCP',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/inverted-minors',
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 169,
    qowner: 'Richard',
    qkey: 'System09',
    qdetail:
      'After the following biddding.   1C  P  3C.  What does this bidding sequence mean ?',
    qcorrect: 'Inverted Minors, Weak, 6 Clubs',
    qbad1: 'Inverted Minors, Weak, 5 Clubs',
    qbad2: 'Inverted Minors, Weak, 7 Clubs',
    qbad3: null,
    qhl1: 'https://www.larryco.com/bridge-articles/inverted-minors',
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 170,
    qowner: 'Richard',
    qkey: 'System10',
    qdetail:
      'After the following biddding.   1H  P  2S.  What does this bidding sequence mean ?',
    qcorrect: 'Bergen Raise.  3 Hearts 10-11 HCP',
    qbad1: 'Drop dead.  6 card suit, weak',
    qbad2: 'Strong  game force',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 171,
    qowner: 'Richard',
    qkey: 'System11',
    qdetail:
      'After the following biddding.   1S  P  3H.  What does this bidding sequence mean ?',
    qcorrect: 'Bergen Raise.  3 Spades 10-11 HCP',
    qbad1: 'Drop dead.  6 card suit, weak',
    qbad2: 'Strong  game force',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 172,
    qowner: 'Richard',
    qkey: 'System12',
    qdetail:
      'After the following biddding.   1S  P  4H.  What does this bidding sequence mean ?',
    qcorrect: 'Splinter, Agreeing Spades as trumps, 11 -14 HCP',
    qbad1: 'To play',
    qbad2: 'Splinter, Agreeing Spades, Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 173,
    qowner: 'Richard',
    qkey: 'System13',
    qdetail:
      'After the following biddding.   1H  P  3S.  What does this bidding sequence mean ?',
    qcorrect: 'Splinter, Agreeing Spades as trumps, 11 -14 HCP',
    qbad1: 'To play',
    qbad2: 'Splinter, Agreeing Spades, Slam interest',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 174,
    qowner: 'Richard',
    qkey: 'System14',
    qdetail:
      'After the following biddding.   1S  X  2S.  What does this bidding sequence mean ?',
    qcorrect: 'Simple raise, can be pre-emptive 3-9 HCP',
    qbad1: 'Simple raise, 2 Spades, pre-emptive',
    qbad2: 'Bergen Raise.  3 Spades 6-9 HCP',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 175,
    qowner: 'Richard',
    qkey: 'System15',
    qdetail:
      'After the following biddding.   1S  P  2S.  What does this bidding sequence mean ?',
    qcorrect: 'Bergen Raise.  3 Spades 6-9 HCP',
    qbad1: 'Simple raise, 2 Spades, pre-emptive',
    qbad2: 'Weak, pre-emptive, 3 spades',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 176,
    qowner: 'Richard',
    qkey: 'System16',
    qdetail:
      'After the following biddding.   1H  P  3C  X,  3D.  What does this bidding sequence mean ?',
    qcorrect: 'Partner to signoff if Min, or bid game if Max',
    qbad1: 'Opener showing Diamonds as a second suit',
    qbad2: 'Opener showing a shortage in Diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 177,
    qowner: 'Richard',
    qkey: 'System17',
    qdetail:
      'After the following biddding.   1H  P  3D.  What does this bidding sequence mean ?',
    qcorrect: 'Bergen raise showing 4 card fit and 10-11 HCP',
    qbad1: 'Bergen raise showing 4 card fit and  HCP6-9',
    qbad2: 'Responder showing weak 7 card diamonds',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 178,
    qowner: 'Richard',
    qkey: 'System18',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2NT, with 6 points and good HEARTS what do you bid ?',
    qcorrect: '3S ',
    qbad1: '3H',
    qbad2: '3H',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 179,
    qowner: 'Richard',
    qkey: 'System19',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2NT, with 4 points and weak HEARTS what do you bid ?',
    qcorrect: '3D',
    qbad1: '3H',
    qbad2: '3C',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 180,
    qowner: 'Richard',
    qkey: 'System20',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2NT, with 6 points and good SPADES what do you bid ?',
    qcorrect: '3NT',
    qbad1: '3S',
    qbad2: '3D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 181,
    qowner: 'Richard',
    qkey: 'System21',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2NT, with 4 points and weak SPADES what do you bid ?',
    qcorrect: '3H',
    qbad1: '3S',
    qbad2: '3D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 182,
    qowner: 'Richard',
    qkey: 'System22',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2H, with 6 points and good HEARTS what do you bid ?',
    qcorrect: 'Pass',
    qbad1: '3H Pre-emptive',
    qbad2: '3D',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 183,
    qowner: 'Richard',
    qkey: 'System23',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2H, with 6 points and good SPADES what do you bid ?',
    qcorrect: 'Pass',
    qbad1: '3S Pre-emptive',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 184,
    qowner: 'Richard',
    qkey: 'System24',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  2S, with 6 points and good HEARTS what do you bid ?',
    qcorrect: 'Pass',
    qbad1: '3H',
    qbad2: '2NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 185,
    qowner: 'Richard',
    qkey: 'System25',
    qdetail:
      'After the following biddding.   2D (Non Vul)   P  3D, with 7 points and good HEARTS what do you bid ?',
    qcorrect: 'Pass',
    qbad1: '3H',
    qbad2: '3NT',
    qbad3: null,
    qhl1: null,
    qhl2: null,
    qgroup1: 'Carol',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 186,
    qowner: 'public',
    qkey: 'WBF01',
    qdetail:
      'https://www.youtube.com/watch?v=XFTnsOm2Xq4&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=76',
    qcorrect: 'Pass',
    qbad1: '2S',
    qbad2: '2NT',
    qbad3: '2D',
    qhl1: 'https://www.youtube.com/watch?v=jh6wnhihDj0',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 187,
    qowner: 'public',
    qkey: 'WBF02',
    qdetail:
      'https://www.youtube.com/watch?v=TsZvW9-Imtc&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=74',
    qcorrect: 'Cross Ruff after cashing aces',
    qbad1: 'Cross Ruff immediately',
    qbad2: 'Draw trumps, then cash Aces',
    qbad3: 'Draw Trumps, then start cross ruffing',
    qhl1: 'https://www.youtube.com/watch?v=u2L8CGoEIeU',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Play',
    qgroup3: null
  },
  {
    qid: 188,
    qowner: 'public',
    qkey: 'WBF03',
    qdetail:
      'https://www.youtube.com/watch?v=_6U0h2afJHE&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=72',
    qcorrect: 'Play on diamonds',
    qbad1: 'Play on clubs',
    qbad2: 'Play on hearts',
    qbad3: 'Play on spades',
    qhl1: 'https://www.youtube.com/watch?v=jh6wnhihDj0',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Play',
    qgroup3: null
  },
  {
    qid: 189,
    qowner: 'public',
    qkey: 'WBF04',
    qdetail:
      'https://www.youtube.com/watch?v=8ruVr0EoL2A&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=70',
    qcorrect: 'Lead Diamonds',
    qbad1: 'Lead Clubs',
    qbad2: 'Lead Hearts',
    qbad3: 'Lead Spades',
    qhl1: 'https://www.youtube.com/watch?v=-1byBDPwLRQ',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Play',
    qgroup3: null
  },
  {
    qid: 190,
    qowner: 'public',
    qkey: 'WBF05',
    qdetail:
      'https://www.youtube.com/watch?v=pdWfV9Hae1c&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=69',
    qcorrect: 'Win in hand, play on Clubs',
    qbad1: 'Win in hand, play on Diamonds',
    qbad2: 'Win in hand, play on Spades',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=sSOMuC7aUyQ',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Play',
    qgroup3: null
  },
  {
    qid: 191,
    qowner: 'public',
    qkey: 'WBF06',
    qdetail:
      'https://www.youtube.com/watch?v=qhV62zvJV3M&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=66',
    qcorrect: '1S',
    qbad1: '1C',
    qbad2: '2S showing 5/4',
    qbad3: 'Multi 2D',
    qhl1: 'https://www.youtube.com/watch?v=stI3glENKv8',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 192,
    qowner: 'public',
    qkey: 'WBF07',
    qdetail:
      'https://www.youtube.com/watch?v=rZKQJnbvRmg&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=64',
    qcorrect: 'Pass',
    qbad1: '2D',
    qbad2: '1NT',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=Y9cqNMjjmsg',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 193,
    qowner: 'public',
    qkey: 'WBF08',
    qdetail:
      'https://www.youtube.com/watch?v=8DCJYS8aiQM&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=60',
    qcorrect: 'Lead a Heart',
    qbad1: 'Lead a Spade',
    qbad2: 'Lead a Diamond',
    qbad3: 'Lead a Club',
    qhl1: 'https://www.youtube.com/watch?v=JfmsF6tkzQE',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Play',
    qgroup3: null
  },
  {
    qid: 194,
    qowner: 'public',
    qkey: 'WBF09',
    qdetail:
      'https://www.youtube.com/watch?v=eypluyv2jLY&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=59',
    qcorrect: 'Lead a Heart',
    qbad1: 'Lead a Spade',
    qbad2: 'Lead a Diamond',
    qbad3: 'Lead a Club',
    qhl1: 'https://www.youtube.com/watch?v=td79IzuF9q0',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Play',
    qgroup3: null
  },
  {
    qid: 195,
    qowner: 'public',
    qkey: 'WBF10',
    qdetail:
      'https://www.youtube.com/watch?v=LNh-xtt2KRw&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=62',
    qcorrect: '2S',
    qbad1: 'Double',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=cp1bsVaAsRE',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 196,
    qowner: 'public',
    qkey: 'WBF11',
    qdetail:
      'https://www.youtube.com/watch?v=SW_6JrllmKc&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=53',
    qcorrect: '2C Stayman',
    qbad1: 'Pass',
    qbad2: 'Systematic transfer to Diamonds',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=x9G4xHGRBJk',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 197,
    qowner: 'public',
    qkey: 'WBF12',
    qdetail:
      'https://www.youtube.com/watch?v=26wCX47i6u8&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=51',
    qcorrect: '2/1 2C Game force',
    qbad1: '2/1 2D Game force',
    qbad2: '3NT',
    qbad3: '4H',
    qhl1: 'https://www.youtube.com/watch?v=_h8VSIxSZoI',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 198,
    qowner: 'public',
    qkey: 'WBF13',
    qdetail:
      'https://www.youtube.com/watch?v=NgFRjCCjCMo&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=50',
    qcorrect: 'Double, Penalty',
    qbad1: '3NT',
    qbad2: 'Double, Take Out',
    qbad3: '2NT Lebensohl',
    qhl1: 'https://www.youtube.com/watch?v=ejKwPcQhogs',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 199,
    qowner: 'public',
    qkey: 'WBF14',
    qdetail:
      'https://www.youtube.com/watch?v=7saKaHoh1Fc&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=48',
    qcorrect: 'Pass',
    qbad1: '2NT',
    qbad2: '3D',
    qbad3: '3H',
    qhl1: 'https://www.youtube.com/watch?v=E16WPGPsnzA',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 200,
    qowner: 'public',
    qkey: 'WBF15',
    qdetail:
      'https://www.youtube.com/watch?v=WCGBZNWoY7o&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=44',
    qcorrect: '4H',
    qbad1: '3H',
    qbad2: '2H',
    qbad3: '4D',
    qhl1: 'https://www.youtube.com/watch?v=nHG01wsPLg4',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 201,
    qowner: 'public',
    qkey: 'WBF16',
    qdetail:
      'https://www.youtube.com/watch?v=gs161tAhc4A&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=41',
    qcorrect: 'Redouble',
    qbad1: '1S',
    qbad2: '1NT',
    qbad3: '2H',
    qhl1: 'https://www.youtube.com/watch?v=jscHL2gmC20',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 202,
    qowner: 'public',
    qkey: 'WBF17',
    qdetail:
      'https://www.youtube.com/watch?v=TVlYY8rzLM0&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=40',
    qcorrect: '2/1 2D Game Force',
    qbad1: '1S',
    qbad2: null,
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=NBxBT3oPaOA',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 203,
    qowner: 'public',
    qkey: 'WBF18',
    qdetail:
      'https://www.youtube.com/watch?v=PnpUJxh5YY8&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=38',
    qcorrect: '4C Splinter ',
    qbad1: '3S Invitational',
    qbad2: '4S',
    qbad3: '3D forcing',
    qhl1: 'https://www.youtube.com/watch?v=egdR3HhtDuc',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 204,
    qowner: 'public',
    qkey: 'WBF19',
    qdetail:
      'https://www.youtube.com/watch?v=thq3P6caT7o&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=36',
    qcorrect: '3H',
    qbad1: '3NT',
    qbad2: '4H',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=AcPx7GY80fg',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 205,
    qowner: 'public',
    qkey: 'WBF20',
    qdetail:
      'https://www.youtube.com/watch?v=Qo6LIWMTGeo&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=34',
    qcorrect: '2H',
    qbad1: 'Double',
    qbad2: '2D',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=nosiNcsP_60',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 206,
    qowner: 'public',
    qkey: 'WBF21',
    qdetail:
      'https://www.youtube.com/watch?v=StJtgZm_kSM&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=32',
    qcorrect: 'Pass',
    qbad1: '1NT',
    qbad2: '2S preemptive',
    qbad3: 'Redouble',
    qhl1: 'https://www.youtube.com/watch?v=8ZiMBLVtd9c',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 207,
    qowner: 'public',
    qkey: 'WBF22',
    qdetail:
      'https://www.youtube.com/watch?v=heFisuDLo44&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=30',
    qcorrect: '4S',
    qbad1: 'Double',
    qbad2: '4NT',
    qbad3: 'Pass',
    qhl1: 'https://www.youtube.com/watch?v=nvwE-WpldQo',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 208,
    qowner: 'public',
    qkey: 'WBF23',
    qdetail:
      'https://www.youtube.com/watch?v=KAmzSaqvvWE&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=28',
    qcorrect: '5C',
    qbad1: '4H',
    qbad2: '4NT',
    qbad3: '4C',
    qhl1: 'https://www.youtube.com/watch?v=egZx18vJVuM',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 209,
    qowner: 'public',
    qkey: 'WBF24',
    qdetail:
      'https://www.youtube.com/watch?v=MbfwoU_6WQU&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=27',
    qcorrect: '3H',
    qbad1: '3D',
    qbad2: '4S',
    qbad3: 'Double',
    qhl1: 'https://www.youtube.com/watch?v=glZnnsR0Wo8',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 210,
    qowner: 'public',
    qkey: 'WBF25',
    qdetail:
      'https://www.youtube.com/watch?v=4F3Hs-64CZM&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=25',
    qcorrect: '1S',
    qbad1: '2S showing 5/4',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=vhH2SMiPN9o',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 211,
    qowner: 'public',
    qkey: 'WBF26',
    qdetail:
      'https://www.youtube.com/watch?v=Nx0UTV1ymQU&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=23',
    qcorrect: 'Double',
    qbad1: '2S',
    qbad2: '3D',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=sGx6wogAGAQ',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 212,
    qowner: 'public',
    qkey: 'WBF27',
    qdetail:
      'https://www.youtube.com/watch?v=haWwQvOxbA0&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=20',
    qcorrect: '3D',
    qbad1: '2D',
    qbad2: 'pass',
    qbad3: '4D',
    qhl1: 'https://www.youtube.com/watch?v=OqxwTi4pkXI',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 213,
    qowner: 'public',
    qkey: 'WBF28',
    qdetail:
      'https://www.youtube.com/watch?v=DDA2u5B_jNg&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=14',
    qcorrect: 'Pass',
    qbad1: '2S',
    qbad2: '2NT',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=zV2Ih7PqsGk',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 214,
    qowner: 'public',
    qkey: 'WBF29',
    qdetail:
      'https://www.youtube.com/watch?v=Pm-6EiBFaSo&list=PLpTZMBT2rnfEfJSu9rop3cxuTbIKL5wVj&index=18',
    qcorrect: '1S',
    qbad1: 'Pass',
    qbad2: null,
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=klpb3lHbgOA',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 215,
    qowner: 'public',
    qkey: 'WBF30',
    qdetail: 'https://www.youtube.com/watch?v=71mwnR0BC18',
    qcorrect: '1NT 15-17',
    qbad1: '1D',
    qbad2: null,
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=x6x1fF2fLpY',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 216,
    qowner: 'public',
    qkey: 'WBF31',
    qdetail: 'https://www.youtube.com/watch?v=AFj_ArhyNWw',
    qcorrect: '2C',
    qbad1: 'Pass',
    qbad2: 'Redouble',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=SfQXCUOQTKg',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 217,
    qowner: 'public',
    qkey: 'WBF32',
    qdetail: 'https://www.youtube.com/watch?v=S1dC5I_zO50',
    qcorrect: '2S',
    qbad1: 'Pass',
    qbad2: '3C',
    qbad3: 'Double',
    qhl1: 'https://www.youtube.com/watch?v=06VczJedIb8',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 218,
    qowner: 'public',
    qkey: 'WBF33',
    qdetail: 'https://www.youtube.com/watch?v=m6-erhM0XeA',
    qcorrect: '3H',
    qbad1: '2H',
    qbad2: 'Pass',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=E-UARFd9JmQ',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  },
  {
    qid: 219,
    qowner: 'public',
    qkey: 'WBF34',
    qdetail: 'https://www.youtube.com/watch?v=HtlNh_3qxt0',
    qcorrect: '2D',
    qbad1: '3S',
    qbad2: '4S',
    qbad3: null,
    qhl1: 'https://www.youtube.com/watch?v=zsGeGlYC7v0',
    qhl2: null,
    qgroup1: 'WBF',
    qgroup2: 'Bidding',
    qgroup3: null
  }
]
